### ISSUE TITLE
conflict with `abbrev-mode`

### ISSUE THREAD

**Issue by BrianZbr** [davidshepherd7/aggressive-fill-paragraph-mode#10]
In the minor mode `abbrev-mode`, inserting a space after an abbreviation is supposed to trigger that abbreviation to be expanded. But when `aggressive-fill-paragraph-mode` is also enabled, that no longer happens.

My elisp skills are minimal, but I think telling `afp-fill-then-insert-space` to run `expand-abbrev` if `abbrev-mode` is active should work, at least as a quick fix anyway.

**Comment by davidshepherd7** [comment]
That would work, but I think a more elegant solution would be to somehow emulate the call to `self-insert-function` that pressing space would normally cause. If I can get that working then any mode which does things after pressing space will work as normal.

Or I might try using `post-self-insert-hook` instead of rebinding space.

Either way I'll get it fixed :)

**Comment by davidshepherd7** [comment]
There's a fix on the unstable branch, but I've made a lot of changes to how the code works so I'm going to try it out for a week or so before I move it to master.

I think the only user visible changes are:
1. This bug is fixed
2. It now auto fills when you type `.` as well as just space (this is customisable with `afp-fill-keys`).

**Comment by BrianZbr** [comment]
Nice! Drop a line here if you push it to ELPA and I will give it a try.

**Comment by davidshepherd7** [comment]
I've merged it, so it should appear on MELPA sometime soon.

**Comment by BrianZbr** [comment]
Thanks for this! I'm finally testing the new version and noticed something very minor. Placement of the cursor after a multi-line expansin seems to be affected.

For example, I have dabbrev like this:

```
#+BEGIN_COMMENT

#+END_COMMENT
```

Normally when this gets expanded, the cursor ends up after the _last_ line. With aggressive-fill-paragraph enabled, the cursor instead ends up near the start of the _second_ line. 

This is unexpected behavior, but really no problem at all as far as I am concerned.

**Comment by davidshepherd7** [comment]
Hmm, that's strange. Do you mean an abbrev rather than a [dabbrev](http://www.emacswiki.org/emacs/DynamicAbbreviations)? If so can you post the definition so I can try it out please?

**Comment by BrianZbr** [comment]
You're right, abbrev. And looking more carefully, I see that it does _not_ actually happen in the simple example I gave earlier, but rather in babel source code blocks. So here are some examples:

```
(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("cm" "#+BEGIN_COMMENT

#+END_COMMENT")
    ("srce" "#+BEGIN_SRC emacs-lisp

#+END_SRC ")
    ("srcp" "#+BEGIN_SRC python

#+END_SRC")
   ))
```

Expanding `cm` works as expected but `srce` and `srcp` do not.

**Comment by davidshepherd7** [comment]
I can't seem to reproduce it with the default org-mode settings. When I type `srcp |` I get

```
#+BEGIN_SRC python

#+END_SRC |
```

(where `|` represents the cursor). I get the same result with/without aggressive-fill-paragraph mode enabled.

Do you have any other settings that could be affecting this? Maybe something that changes the effective mode inside source blocks or something like that?

**Comment by BrianZbr** [comment]
I tried it from a clean init, but I guess it must just be something odd on my end. Sorry for the trouble but thanks again for all the support!

**Comment by davidshepherd7** [comment]
No problem :)
